// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCqaqXyCvKqyaKvP0T-9vXg0mIyXOevpvo',
    appId: '1:392701292758:web:abf623ac94d7d0ef121977',
    messagingSenderId: '392701292758',
    projectId: 'drivadnew',
    authDomain: 'drivadnew.firebaseapp.com',
    storageBucket: 'drivadnew.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ9-dOL0oWNtweIqYXLkC8k42ljqkt040',
    appId: '1:392701292758:android:3be61e22a0d40ad7121977',
    messagingSenderId: '392701292758',
    projectId: 'drivadnew',
    storageBucket: 'drivadnew.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuFycJKQaJowrVt8S0TaO7M-SEnhBAG48',
    appId: '1:392701292758:ios:6d28a302bcb57730121977',
    messagingSenderId: '392701292758',
    projectId: 'drivadnew',
    storageBucket: 'drivadnew.firebasestorage.app',
    iosBundleId: 'com.example.drivadApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuFycJKQaJowrVt8S0TaO7M-SEnhBAG48',
    appId: '1:392701292758:ios:6d28a302bcb57730121977',
    messagingSenderId: '392701292758',
    projectId: 'drivadnew',
    storageBucket: 'drivadnew.firebasestorage.app',
    iosBundleId: 'com.example.drivadApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqaqXyCvKqyaKvP0T-9vXg0mIyXOevpvo',
    appId: '1:392701292758:web:a2cab8f9283f763a121977',
    messagingSenderId: '392701292758',
    projectId: 'drivadnew',
    authDomain: 'drivadnew.firebaseapp.com',
    storageBucket: 'drivadnew.firebasestorage.app',
  );
}
